- name: Michael Sarahan
  email: msarahan@gmail.com
  github: msarahan
  alternate_emails:
  - msarahan@continuum.io
  - msarahan@anaconda.com
  aliases:
  - Mike Sarahan
  num_commits: 73
  first_commit: 2019-01-03 20:00:40
- name: Nehal J Wani
  email: nehaljw.kkd1@gmail.com
  num_commits: 2
  first_commit: 2019-05-01 08:25:27
  github: nehaljwani
